<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1 (Python 3.10.7 on win32)" generated="20221006 17:04:43.396" rpa="false" schemaversion="3">
<suite id="s1" name="Testes" source="C:\Users\fabriciosantos\Documents\POC Robot\testes.robot">
<test id="s1-t1" name="Fazer login no power apps" line="9">
<kw name="open chrome" type="SETUP">
<msg timestamp="20221006 17:04:43.518" level="FAIL">No keyword with name 'open chrome' found.</msg>
<status status="FAIL" starttime="20221006 17:04:43.518" endtime="20221006 17:04:43.518"/>
</kw>
<kw name="Close" type="TEARDOWN">
<msg timestamp="20221006 17:04:43.520" level="FAIL">No keyword with name 'Close' found.</msg>
<status status="FAIL" starttime="20221006 17:04:43.520" endtime="20221006 17:04:43.520">No keyword with name 'Close' found.</status>
</kw>
<status status="FAIL" starttime="20221006 17:04:43.515" endtime="20221006 17:04:43.522">Setup failed:
No keyword with name 'open chrome' found.

Also teardown failed:
No keyword with name 'Close' found.</status>
</test>
<status status="FAIL" starttime="20221006 17:04:43.397" endtime="20221006 17:04:43.524"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Testes">Testes</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221006 17:04:43.513" level="ERROR">Error in file 'C:\Users\fabriciosantos\Documents\POC Robot\testes.robot' on line 3: Resource file '.POloginPO.robot' does not exist.</msg>
<msg timestamp="20221006 17:04:43.514" level="ERROR">Error in file 'C:\Users\fabriciosantos\Documents\POC Robot\testes.robot' on line 4: Resource file '.Resourceesource.robot' does not exist.</msg>
</errors>
</robot>
